/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alexis_libstardict_Index */

#ifndef _Included_org_alexis_libstardict_Index
#define _Included_org_alexis_libstardict_Index
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alexis_libstardict_Index
 * Method:    getRawWords
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_alexis_libstardict_Index_getRawWords
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alexis_libstardict_Index
 * Method:    getRawLetter
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_alexis_libstardict_Index_getRawLetter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alexis_libstardict_Index
 * Method:    getWord
 * Signature: (Ljava/lang/String;)Lorg/alexis/libstardict/Word;
 */
JNIEXPORT jobject JNICALL Java_org_alexis_libstardict_Index_getWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alexis_libstardict_Index
 * Method:    getWordFromId
 * Signature: (I)Lorg/alexis/libstardict/Word;
 */
JNIEXPORT jobject JNICALL Java_org_alexis_libstardict_Index_getWordFromId
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
